project:
  type: website
  output-dir: docs

website:
  
  title: "UAZ CAST Data Literacy Project"
  navbar:
    logo: https://cdn.uadigital.arizona.edu/logos/v1.0.0/ua_wordmark_line_logo_white_rgb.min.svg
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: walkthrough.qmd
        text: Tutorials 
        menu:
          - contact.qmd
          - text: Something
      - href: team.qmd
        text: Team
      - href: contact.qmd
        text: Contact




  page-footer: 
    background: dark
    left: "Copyright 2022, UAZ CAST DATA LITERACY PROJECT" 
    right: 
      - icon: github
        href: https://github.com/UAZcast-dataliteracy
       
       

  
       

format:
  html:
    theme: simplex
    css: styles.css
    toc: true



